config/routes.rb
Rails.application.routes.draw do
  resources :dashboards

  get 'welcome/dashboard'

  root 'welcome#dashboard'

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, only: [:show, :edit, :update, :destroy]

  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_params
      params.fetch(:dashboard, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dashboards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dashboards.each do |dashboard| %>
      <tr>
        <td><%= link_to 'Show', dashboard %></td>
        <td><%= link_to 'Edit', edit_dashboard_path(dashboard) %></td>
        <td><%= link_to 'Destroy', dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dashboard', new_dashboard_path %>

app/views/dashboards/new.html.erb
<h1>New Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FootyRedesign</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/dashboard.html.erb
<div class="sitewrap">
	<header class="header">
		<div class="brand">
			<h1><a href="/" class="logo">FootyPlan<img src="https://cdn.footyplan.com/assets/logo-f018ec861601dda4e77f05549dc1f76e.png" alt="Footy Plan Logo"></a></h1>
		</div>
		<div class="sidebar-toggle">
			<div class="fa fa-bars"></div>
		</div>
		<nav class="notify">
			<ul class="nav">
				<li class="dropdown">
					<a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="true">
						<i class="fa fa-flag"></i>
						<span class="badge bg-success">3</span>
					</a>
					<ul class="dropdown-menu">
						<li><p>notification info goes here</p></li>
						<li><p>notification info goes here</p></li>
						<li><p>notification info goes here</p></li>
					</ul>
				</li>
				<li class="dropdown">
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
						<i class="fa fa-envelope"></i>
						<span class="badge bg-important">4</span>
					</a>
					<ul class="dropdown-menu">
						<li><p>message 1</p></li>
						<li><p>message 2</p></li>
						<li><p>message 3</p></li>
						<li><p>message 4</p></li>
					</ul>
				</li>
				<li>
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
						<i class="fa fa-bell"></i>
						<span class="badge bg-warning">3</span>
					</a>
					<ul class="dropdown-menu">
						<li><p>notification 1</p></li>
						<li><p>notification 2</p></li>
						<li><p>notification 3</p></li>
					</ul>
				</li>
			</ul>
		</nav>
		<div class="menu-right">
			<ul class="nav">
				<li class="dropdown">
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
						<img alt="" src="avatar.jpg">
						<span class="username">John Doe</span>
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><p>Profile</p></li>
						<li><p>Settings</p></li>
						<li><p>Log Out</p></li>
					</ul>
				</li>
				<li><div class="sidebar-toggle">
						<div class="fa fa-question" onclick="Intercom('showNewMessage')"></div>
					</div></li>
				<li>
					<div class="sidebar-toggle">
						<div class="fa fa-comment"></div>
					</div>
				</li>
			</ul>
		</div>
	</header>
	<aside class="left-sidebar">
		<nav class="left-nav">
			<ul class="nav">
				<li><a href="#" class="active"><i class="fa fa-dashboard"></i>Dashboard</a></li>
				<li><a href="#"><i class="fa fa-table"></i>Session Builder</a></li>
				<li><a href="#"><i class="fa fa-envelope"></i>Messenger</a></li>
				<li><a href="#"><i class="fa fa-th-large"></i>Calendar</a></li>
				<li><a href="#"><i class="fa fa-send"></i>Referral Program</a></li>
			</ul>
		</nav>
	</aside>
	<main class="main-content">
		<div class="wrapper container-fluid">
			<div class="row">
				<div class="col-md-4">
					<section class="panel">
						<div class="panel-body">
							<h4>Panel Title</h4>
							<p>Panel content goes here.</p>
							<img src="http://placehold.it/350x250/eb007f/ffffff?text=Footy Graph">
						</div>
					</section>
				</div>
				<div class="col-md-4">
					<section class="panel">
						<div class="panel-body">
							<h4>Panel Title</h4>
							<p>Panel content goes here.</p>
							<img src="http://placehold.it/350x250/8cc831/ffffff?text=Footy Graph">
						</div>
					</section>
				</div>
				<div class="col-md-4">
					<section class="panel">
						<div class="panel-body">
							<h4>Panel Title</h4>
							<p>Panel content goes here.</p>
							<img src="http://placehold.it/350x250/00a6f6/ffffff?text=Footy Graph">
						</div>
					</section>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8">
					<section class="panel">
						<div class="panel-heading">
							<h4>Panel Heading Title</h4>
						</div>
						<div class="panel-body">
							<p>Panel body content goes here.</p>
							<img src="http://placehold.it/500/00a6f6/ffffff?text=Footy Graph">
						</div>
					</section>
				</div>
				<div class="col-md-4">
					<section class="panel">
						<div class="panel-heading">
							<h4>Panel Heading Title</h4>
						</div>
						<div class="panel-body">
							<p>Panel content goes here.</p>
							<img src="http://placehold.it/350x250/eb007f/ffffff?text=Footy Graph">
						</div>
					</section>
				</div>
			</div>
		</div>
	</main>
	<div class="right-sidebar">
		<div class="content">
			<h3>Messenger</h3>
		</div>
	</div>
</div>